### ISSUE TITLE
New content not present

### ISSUE THREAD

**Issue by starscollide5** [endless-sky/all-content-plugin#16]
Endless Sky received new ships & outfits since mid-2018, any chance it will be added?

**Comment by tehhowch** [comment]
Alongside the v0.9.9 release of the game will be the v0.9.9 release of the all-content-plugin. ETA 1 month I think.

**Comment by starscollide5** [comment]
The game was released, hopefully it won't take too long for plugin to be updated.

**Comment by starscollide5** [comment]
I updated the files to match current 0.9.9 version. I'm not familiar with git at all, so I created these pull requests:
#17 
#18 
#19
