### ISSUE TITLE
Ships that don't have a category aren't shown in the shipyard, even though they are present in "All Ships"

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/all-content-plugin#9]
Pertains to Hallucinations, Nanobots and Timer Ships.

**Comment by Bladewood** [comment]
It's not logical for the player to have access to almost all of these, so the only real solution is to remove them from the list.
The single exception is the Hallucination, the only one of these ships that is actually visible and therefore probably won't end up [crashing the game](https://github.com/endless-sky/endless-sky/issues/1672); cf. void sprites and archons, which are all unobtainable for obvious reasons and yet [are allowed to be piloted](https://github.com/endless-sky/all-content-plugin/pull/4).
In the Hallucination's case, we might have to give it a proper category, but that's an issue for the [endless-sky](https://github.com/endless-sky/endless-sky) repository.

**Comment by Tadrix** [comment]
Just a head-up: Before posting this issue I did my homework and tested them after giving them a category. The game didn't crash. In fact, 100 nanobots did marvelous job clearing the Shaula system of any and all pirates (while some of them died too, presumably to splash damage from explosions). In other words, they function as they should.

AFAIK this plugin functions primarily as a test aid (cheating is a secondary function). An option to take deliberate amount of nanobots along for testing purposes is one of possible uses and in my opinion should be covered.

**Comment by tehhowch** [comment]
Can probably be remedied easily by stubbing the definition in this plugin. There's no reason to modify the category of the ship in the actual game repo - just do it here:

```
ship "Nanobot"
    add attributes
        category "Heavy Warship"

ship "Timer Ship"
    add attributes
        category "Interceptor"

ship "Hallucination"
    add attributes
        category "Interceptor"
```

**Comment by Tadrix** [comment]
Good thought. Addressing this in #11.
